### ISSUE TITLE
[FEAT] 사업장 정보입력 UI 구현 

### ISSUE THREAD

**Issue by lenamin** [Hongmoon-gak/First-CEO-iOS#1]
## 💡 Issue

사업장 정보입력 기능의 UI를 구현합니다. 

## 📝  todo
- [ ] 공통
    - [ ] Progress bar 구현
    - [ ] 다음 버튼 구현 
    - [ ] color 등록 (pointNavy, backgroundNavy, progressGray, backgroundGray)

- [ ] NameQuestionView
    - [ ] text field 구현 
 
- [ ] KindQuestionView
    - [ ] 업종 분류 collectionView 구현 

- [ ] SizeQuestionView, ProfitQuestionView
    - [ ] tableView 구현 

## 📸 Screenshot

<img width="762" alt="Screenshot 2023-07-16 at 21 46 17" src="https://github.com/Hongmoon-gak/First-CEO-iOS/assets/99120199/9d424256-6e65-4c1c-849d-34fe85bfbc7f">
