### ISSUE TITLE
[FEAT] 관련 법령 보기 중 1. 4대보험 뷰 구현 

### ISSUE THREAD

**Issue by lenamin** [Hongmoon-gak/First-CEO-iOS#6]
## 💡 Issue

- 4대 보험 뷰를 구현합니다 

## 📝  todo
- [x] 상단 고정 custom segment 구현
- [x] 4대보험 설명 뷰 구현
- [x] 4대보험 종류 뷰 구현 
- [x] 4대보험 요율 차트 삽입 
- [x] 4대보험 계산기 웹뷰 연결 구현 

## 📸 Screenshot

<img width="189" alt="Screenshot 2023-07-26 at 12 49 29" src="https://github.com/Hongmoon-gak/First-CEO-iOS/assets/99120199/1c67e870-dbde-4236-9c75-9e0d26b454ab">
