### ISSUE TITLE
[FEAT] 관련법령 (근로계약, 급여, 해고) 뷰 구현 

### ISSUE THREAD

**Issue by lenamin** [Hongmoon-gak/First-CEO-iOS#9]
## 💡 Issue

관련법령 Segmented Control에 포함될 뷰를 구현합니다. (근로계약, 급여, 해고) 

## 📝  todo
- [ ] 근로계약 뷰를 구현합니다 (근로계약서 양식 다운로드 기능 구현 포함 - fileManager 통해 로컬에 파일 저장)
- [ ] 급여 뷰를 구현합니다 (급여명세서 양식 다운받기 기능 구현 포함 - fileManager 통해 로컬에 파일 저장)
- [ ] 해고 뷰를 구현합니다 

## 📸 Screenshot

<img width="673" alt="Screenshot 2023-08-09 at 16 21 53" src="https://github.com/Hongmoon-gak/First-CEO-iOS/assets/99120199/41aeb14d-7bb6-473d-a2af-ba498e8080ef">
